name: Deploy the latest documentation
on:
  push:
    tags:
      - "v*"
jobs:
  deploy:
    name: Deploy the latest documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r mkdocs mkdocs-material mike
        env:
          GH_TOKEN: ${{ secrets.MKDOCS_AQUA_BOT }}
      - name: Configure the git user
        run: |
          git config user.name "Ryan Kowalewski"
          git config user.email "ryan@ryanjan.uk"
      - name: Deploy the latest documents from new tag push
        if: ${{ github.event.inputs.version == '' }}
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          mike deploy --push --update-aliases $VERSION latest